sual_dp = [
    # Şəxsi maraqlar və seçimlər
    "Ən sevdiyiniz film hansıdır?",
    "Ən çox hansı musiqi janrını dinləyirsiniz?",
    "Sevdiyiniz rəssam kimdir?",
    "Ən çox hansı yeməyi bişirməyi sevirsiniz?",
    "Hansı mövzuda kitablar oxumağı sevirsiniz?",
    "Ən çox ziyarət etmək istədiyiniz ölkə hansıdır?",
    "Ən çox sevdiyiniz rəng hansıdır?",
    "Uşaqlıqdan yadınızda qalan ən gözəl xatirə hansıdır?",
    "Ən çox sevdiyiniz idman növü hansıdır?",
    "Hansı dili öyrənmək istərdiniz?",
    "Ən çox sevdiyiniz heyvan hansıdır?",
    "Hansı növ çiçəkləri sevirsiniz?",
    "Ən çox sevdiyiniz şirniyyat hansıdır?",
    "Hansı avtomobil markasını daha çox bəyənirsiniz?",
    "Ən çox sevdiyiniz mövsüm hansıdır?",
    "Ən çox sevdiyiniz şəhər haradır?",
    "Ən çox sevdiyiniz təbiət mənzərəsi hansıdır?",
    "Ən çox sevdiyiniz bayram hansıdır?",
    "Sevdiyiniz kitab qəhrəmanı kimdir?",
    "Ən çox hansı rəqsi sevirsiniz?",
    "Ən çox sevdiyiniz dondurma növü hansıdır?",
    "Ən çox sevdiyiniz meyvə hansıdır?",
    "Ən çox hansı fəsildə tətil etməyi sevirsiniz?",
    "Ən çox sevdiyiniz tarix dövrü hansıdır?",
    "Ən çox sevdiyiniz aktyor kimdir?",
    "Hansı musiqi alətində çalmağı öyrənmək istərdiniz?",
    "Ən çox hansı rənglərdən istifadə edirsiniz?",
    "Hansı məşhur şəxsiyyətlə görüşmək istərdiniz?",
    "Ən çox sevdiyiniz cizgi filmi hansıdır?",
    "Ən çox sevdiyiniz nağıl hansıdır?",
    "Ən çox sevdiyiniz qoxu hansıdır?",
    "Ən çox sevdiyiniz restoran hansıdır?",
    "Ən çox hansı idman yarışlarını izləməyi sevirsiniz?",
    "Hansı sahədə ixtisaslaşmaq istəyirsiniz?",
    "Ən çox hansı növ filmləri sevirsiniz?",
    "Hansı növ şorbalardan xoşunuz gəlir?",
    "Ən çox sevdiyiniz qəlyanaltı hansıdır?",
    "Ən çox sevdiyiniz içki hansıdır?",
    "Hansı ölkənin mətbəxini daha çox bəyənirsiniz?",
    "Ən çox sevdiyiniz ailəvi fəaliyyət hansıdır?",
    "Ən çox hansı təbiət hadisəsini seyr etməyi sevirsiniz?",
    "Hansı texnologiya sizi daha çox heyrətləndirir?",
    "Ən çox hansı tətbiqdən istifadə edirsiniz?",
    "Hansı məşhur sənət əsərini canlı görmək istərdiniz?",
    "Hansı mövzuda araşdırmalar aparmağı sevirsiniz?",
    "Ən çox sevdiyiniz çay növü hansıdır?",
    "Ən çox sevdiyiniz hava şəraiti hansıdır?",
    "Ən çox sevdiyiniz tarixi abidə hansıdır?",
    "Ən çox sevdiyiniz yazıçı kimdir?",
    "Hansı növ sənət əsərləri sizi cəlb edir?",
    "Ən çox hansı növ pizzanı sevirsiniz?",
    "Hansı mövzuda təqdimat hazırlamaq istərdiniz?",
    "Ən çox hansı növ musiqi alətləri sizi cəlb edir?",
    "Hansı idman komandasına azarkeşlik edirsiniz?",
    "Ən çox sevdiyiniz klassik musiqi əsəri hansıdır?",
    "Ən çox sevdiyiniz qrup hansıdır?",
    "Hansı növ çaydan istifadə edirsiniz?",
    "Ən çox sevdiyiniz bulud forması hansıdır?",
    "Hansı məşhur tarixçi sizi daha çox maraqlandırır?",
    "Hansı mövzuda müzakirələrə qoşulmağı sevirsiniz?",
    "Ən çox hansı tarixi filmləri izləməyi sevirsiniz?",
    "Ən çox hansı şəhərin gecə mənzərəsini bəyənirsiniz?",
    "Ən çox hansı növ çərəzləri sevirsiniz?",
    "Ən çox hansı növ meşələri bəyənirsiniz?",
    "Hansı mövzuda seminar keçmək istərdiniz?",
    "Hansı sahədə özünüzü inkişaf etdirmək istəyirsiniz?",
    "Ən çox sevdiyiniz aksiyon filmi hansıdır?",
    "Hansı növ rəqəmsal alətləri istifadə edirsiniz?",
    "Ən çox sevdiyiniz bulvar haradadır?",
    "Hansı sahədə innovasiya yaratmaq istərdiniz?",
    "Ən çox hansı mövzuda sənədli filmləri izləyirsiniz?",
    "Hansı mövzuda TED çıxışı etmək istərdiniz?",
    "Ən çox hansı növ kitablar sizi cəlb edir?",
    "Hansı məşhur elm adamı ilə görüşmək istərdiniz?",
    "Hansı sahədə könüllü olmaq istərdiniz?",
    "Hansı növ ev heyvanlarını sevirsiniz?",
    "Ən çox hansı təbiət parkını ziyarət etmək istərdiniz?",
    "Ən çox hansı növ idman geyimlərini sevirsiniz?",
    "Ən çox hansı növ musiqi festivallarına qatılmaq istərdiniz?",
    "Hansı məşhur rəssamın əsərlərini sevirsiniz?",
    "Ən çox hansı mövzuda bloq yazmaq istərdiniz?",
    "Hansı mövzuda oyun hazırlamaq istərdiniz?",
    "Ən çox hansı növ sərgiləri ziyarət etməyi sevirsiniz?",
    "Hansı mövzuda kitab yazmaq istərdiniz?",
    "Hansı növ heyvan sığınacaqlarında işləmək istərdiniz?",
    "Ən çox hansı növ sənət əsərlərini sevirsiniz?",
    "Ən çox hansı mövzuda film çəkmək istərdiniz?",
    "Hansı növ təhsil proqramlarını daha çox bəyənirsiniz?",
    "Ən çox hansı mövzuda layihələrdə iştirak etmək istərdiniz?",
    "Hansı növ komediya filmlərini sevirsiniz?",
    "Hansı sahədə ixtira etmək istərdiniz?",
    "Ən çox hansı mövzuda təlimlərdə iştirak etmək istərdiniz?",
    "Hansı növ macəra fəaliyyətlərini sevirsiniz?",
    "Ən çox hansı mövzuda sənət əsərləri sizi ilhamlandırır?",
    "Hansı mövzuda beynəlxalq layihələrdə iştirak etmək istərdiniz?",
    "Hansı sahədə startap qurmaq istərdiniz?",
    "Ən çox hansı növ mənzərələri çəkirsiniz?",
    "Hansı növ texnoloji cihazları daha çox istifadə edirsiniz?",
    "Hansı mövzuda sosial kampaniyalarda iştirak etmək istərdiniz?",
    "Hansı növ tarix dərslərini sevirsiniz?",
    "Hansı mövzuda elmi məqalələr yazmaq istərdiniz?",
    "Hansı növ tarixi romanları sevirsiniz?",
    "Hansı mövzuda mühazirələrə qatılmaq istərdiniz?",
    "Hansı növ mədəniyyət festivallarını sevirsiniz?",
    "Hansı mövzuda mühazirələrdə iştirak etmək istərdiniz?",
    "Hansı mövzuda icmalar yaratmaq istərdiniz?",
    "Hansı növ tarix kitablarını oxumağı sevirsiniz?"
    "Ən sevdiyiniz rəng hansıdır?",
    "Ən son oxuduğunuz kitab nədir?",
    "Sevdiyiniz musiqi janrı hansıdır?",
    "Hansı ölkəyə səyahət etmək istərdiniz?",
    "Uşaqlıq arzunuz nə idi?",
    "Ən sevdiyiniz yemək hansıdır?",
    "Həyatınızda ən böyük uğurunuz nədir?",
    "Gələcəkdə hansı sahədə çalışmaq istəyirsiniz?",
    "Ən çox hansı mövzuda filmləri sevirsiniz?",
    "Sizə motivasiya verən şey nədir?",
    "Daha çox səhər insanısınız, yoxsa gecə?",
    "Ən sevdiyiniz heyvan hansıdır?",
    "Ən çox istifadə etdiyiniz sosial şəbəkə hansıdır?",
    "Ən çox ziyarət etmək istədiyiniz şəhər hansıdır?",
    "Hansı idman növü ilə maraqlanırsınız?",
    "Ən çox sevdiyiniz mövsüm hansıdır?",
    "Daha çox çay içirsiniz, yoxsa qəhvə?",
    "Ən çox sevdiyiniz cizgi filmi hansıdır?",
    "Uşaqlıqda ən çox hansı oyunu oynayırdınız?",
    "Ən çox sevdiyiniz şirniyyat hansıdır?",
    "Hansı dildə danışmağı öyrənmək istərdiniz?",
    "Ən sevdiyiniz idmançı kimdir?",
    "Ən çox istifadə etdiyiniz tətbiq hansıdır?",
    "Ən çox sevdiyiniz film rejissoru kimdir?",
    "Hansı musiqi alətində çalmağı bacarırsınız?",
    "Ən sevdiyiniz bayram hansıdır?",
    "Hansı tarixi şəxsiyyəti görmək istərdiniz?",
    "Ən çox sevdiyiniz aktyor və ya aktrisa kimdir?",
    "Hansı super gücə sahib olmaq istərdiniz?",
    "Ən çox sevdiyiniz serial hansıdır?",
    "Uşaqlıqda ən çox hansı fənni sevirdiniz?",
    "Hansı kitab sizi daha çox təsirləndirib?",
    "Hansı dəniz və ya okean sahilində olmaq istərdiniz?",
    "Ən çox sevdiyiniz meyvə hansıdır?",
    "Daha çox şəhər həyatını, yoxsa kənd həyatını sevirsiniz?",
    "Ən çox sevdiyiniz rəssam kimdir?",
    "Hansı avtomobil markasını sevirsiniz?",
    "Ən çox sevdiyiniz komediya filmi hansıdır?",
    "Ən çox hansı dilə qulaq asmağı sevirsiniz?",
    "Hansı məşhurla nahar etmək istərdiniz?",
    "Ən çox sevdiyiniz desert hansıdır?",
    "Hansı işlə məşğul olmaq istərdiniz?",
    "Ən çox hansı təbiət mənzərəsini sevirsiniz?",
    "Ən çox sevdiyiniz video oyun hansıdır?",
    "Ən çox sevdiyiniz qəhrəman kimdir?",
    "Ən sevdiyiniz rəqs növü hansıdır?",
    "Ən çox hansı kitab janrını sevirsiniz?",
    "Ən sevdiyiniz çiçək hansıdır?",
    "Ən çox hansı şəhərdə yaşamaq istərdiniz?",
    "Hansı peşəni seçməyi arzulayırdınız?",
    "Ən çox sevdiyiniz tarixi dövr hansıdır?",
    "Ən çox sevdiyiniz şair kimdir?",
    "Ən çox sevdiyiniz animasiya filmi hansıdır?",
    "Hansı fəsildə doğulmusunuz?",
    "Ən çox sevdiyiniz ailəvi fəaliyyət hansıdır?",
    "Ən çox sevdiyiniz ulduzlu gecə mənzərəsi haradadır?",
    "Hansı ölkənin mətbəxini daha çox sevirsiniz?",
    "Ən çox sevdiyiniz tarixi abidə hansıdır?",
    "Ən çox sevdiyiniz idman komandası hansıdır?",
    "Ən çox sevdiyiniz tətil yeri haradır?",
    "Hansı təbiət hadisəsini izləməyi sevirsiniz?",
    "Ən çox sevdiyiniz uşaqlıq xatirəsi nədir?",
    "Hansı növ sənət əsərlərinə daha çox maraq göstərirsiniz?",
    "Ən çox sevdiyiniz şorba növü hansıdır?",
    "Ən çox sevdiyiniz yazıçı kimdir?",
    "Ən çox sevdiyiniz şokolad növü hansıdır?",
    "Ən çox sevdiyiniz bayram yeməyi hansıdır?",
    "Hansı təhsil sahəsi sizi daha çox maraqlandırır?",
    "Ən çox sevdiyiniz meşə növü hansıdır?",
    "Ən çox sevdiyiniz sənət növü hansıdır?",
    "Hansı kitab sizi güldürüb?",
    "Ən çox sevdiyiniz aksiyon filmi hansıdır?",
    "Ən çox sevdiyiniz musiqi qrupu hansıdır?",
    "Ən çox sevdiyiniz pizza növü hansıdır?",
    "Hansı hava şəraitində özünüzü daha yaxşı hiss edirsiniz?",
    "Ən çox sevdiyiniz çay növü hansıdır?",
    "Ən çox sevdiyiniz dəniz heyvanı hansıdır?",
    "Ən çox sevdiyiniz şəkər növü hansıdır?",
    "Hansı müasir texnologiya sizi daha çox heyrətləndirir?",
    "Ən çox sevdiyiniz foto növü hansıdır?",
    "Hansı saatda daha çox enerji hiss edirsiniz?",
    "Ən çox sevdiyiniz market hansıdır?",
    "Ən çox sevdiyiniz içki hansıdır?",
    "Hansı ölkənin musiqisini daha çox sevirsiniz?",
    "Ən çox sevdiyiniz həftə günü hansıdır?",
    "Ən çox sevdiyiniz dondurma növü hansıdır?",
    "Ən çox sevdiyiniz nağıl hansıdır?",
    "Hansı film sizə ən çox təsir edib?",
    "Ən çox sevdiyiniz xəmir yeməyi hansıdır?",
    "Ən çox sevdiyiniz otel tipi hansıdır?",
    "Ən çox sevdiyiniz rəng kombinasiyası hansıdır?",
    "Hansı ölkənin mədəniyyəti sizi daha çox maraqlandırır?",
    "Ən çox sevdiyiniz bulud forması hansıdır?",
    "Hansı növ işıqlandırmanı sevirsiniz?"
]
