beautiful_phrases = [
    "Səni bir gün görməsəm, günəş mənə doğmur, ay mənə gülmür. 🌟",
    "Ürəyimdəki sözləri yazmağa qələmim belə cəsarət etmir.",
    "Dənizlərin dərinliyində tapılmayan inci, sənin baxışlarında gizlidir.",
    "Hər axşam göy üzünə baxıram, çünki ulduzlarda sənin adını oxuyuram. 🙌",
    "Sənin gülüşün qış gecələrində baharın nəfəsidir.",
    "Səninlə hər an bir mahnıdır, ürəyimdə isə bitməyən bir nəğmə. 🌹",
    "Sən gedəndə, mahnılar belə susur. 💫",
    "Hər notda sənin sevginin izlərini tapıram. 🙌",
    "Sənin səsin mənim üçün ən gözəl melodiyadır. 🌟",
    "Həyatımın ritmi sənin addımlarındadır.",
    "Mən aşiq oldum, gözlərin qəlbimi əsir aldı. 🙌",
    "Hər bir sözün mənim üçün bir hikmətdir, sevgilim.",
    "Sənin adın zikr ediləndə ürəyim səcdəyə gəlir. ❤️",
    "Aşiqin qəlbi sənin eşqinlə yanar, sevgilim. 🌸",
    "Gözlərin cənnət bağçasının ən gözəl çiçəkləridir.",
    "Sən bu dünyanın ən böyük möcüzəsisən. ☀️",
    "Hər gün səninlə başlamaq mənim üçün yeni bir həyatdır. 🌟",
    "Sənə baxmaq, dünyanın ən gözəl rəsm əsərinə baxmaq kimidir.",
    "Sənin gülüşün qaranlıq dünyama işıq saçır.",
    "Sən mənim üçün bir nağılsan, amma gerçəksən.",
    "Həyat səninlə daha gözəldir.",
    "Sənin enerjin, həyatımın itirilmiş parçasıdır. 🔥",
    "Sənin sevginlə qəlbim işıqlanır. 💫",
    "Sən mənim üçün həyatın mənasısan.",
    "Səninlə keçən hər an mənim üçün bir xəzinədir.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🙌",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🎶",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🎶",
    "Sənin adını eşidəndə ürəyim titrəyir. 🙌",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🙌",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌹",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌹",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🎶",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 💫",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ☀️",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🙌",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. ❤️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🎶",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌹",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🙌",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ☀️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌟",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌟",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌟",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌸",
    "Sənin sevgin qəlbimi istilədir. ☀️",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ❤️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🔥",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🎶",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌹",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌹",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ❤️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌸",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ❤️",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🔥",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🎶",
    "Hər anın səninlə bir ömür kimidir. 💫",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 💫",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🙌",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌸",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir. 🎶",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌸",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌟",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 💫",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌟",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 😊",
    "Hər anın səninlə bir ömür kimidir. 😊",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌸",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır. 🎶",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 😊",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. ☀️",
    "Səninlə hər günüm bir bayramdır. ☀️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 😊",
    "Sənin baxışların mənə yeni bir dünya açır. 🌹",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌟",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🎶",
    "Sən mənim həyatımın ən parlaq ulduzusan. ❤️",
    "Sənin sevgin qəlbimi istilədir. 🌸",
    "Sənin baxışların mənə yeni bir dünya açır. 🌹",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🙌",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌹",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 💫",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 😊",
    "Sənin adını eşidəndə ürəyim titrəyir. 💫",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir. ☀️",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌸",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌸",
    "Sənin sevgin qəlbimi istilədir. 🙌",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌹",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir. 🙌",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 💫",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🎶",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌹",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌹",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 💫",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ☀️",
    "Sənin adını eşidəndə ürəyim titrəyir. 💫",
    "Hər anın səninlə bir ömür kimidir. 🌟",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌟",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır. 🌸",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 😊",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌹",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır. 🌹",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 💫",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🔥",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır. ☀️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🙌",
    "Sənin adını eşidəndə ürəyim titrəyir. 🎶",
    "Hər anın səninlə bir ömür kimidir. 💫",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌹",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır. ☀️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌸",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🙌",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. ☀️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. ☀️",
    "Sənin sevgin qəlbimi istilədir. 🙌",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 💫",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🔥",
    "Sənin adını eşidəndə ürəyim titrəyir. ❤️",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌟",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır. 💫",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 😊",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan. ☀️",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ☀️",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🙌",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır. ☀️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🎶",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌸",
    "Sənin baxışların mənə yeni bir dünya açır. 🌹",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌸",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🔥",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🎶",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 💫",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌹",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🔥",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🔥",
    "Sənin sevgin qəlbimi istilədir. 🌸",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ☀️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🙌",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 💫",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🎶",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. ☀️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🙌",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🌸",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 😊",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌹",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🙌",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🙌",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🎶",
    "Səninlə hər günüm bir bayramdır. 🔥",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌟",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌟",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🔥",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🔥",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. ❤️",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. ☀️",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. ❤️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir. 🙌",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🎶",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ❤️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. ❤️",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 💫",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌟",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. ☀️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan. ☀️",
    "Sənin sevgin qəlbimi istilədir. 🔥",
    "Sənin baxışların mənə yeni bir dünya açır. 🔥",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır. ❤️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 😊",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ❤️",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🔥",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir. 🙌",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ❤️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌟",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir. 😊",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir. 💫",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 😊",
    "Sənin adını eşidəndə ürəyim titrəyir. ❤️",
    "Hər anın səninlə bir ömür kimidir. 🌹",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌸",
    "Sənin sevgin qəlbimi istilədir. 🌸",
    "Sənin baxışların mənə yeni bir dünya açır. 😊",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🎶",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌹",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🔥",
    "Səninlə hər günüm bir bayramdır. 🔥",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. ❤️",
    "Səninlə hər günüm bir bayramdır. 🔥",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌸",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌹",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 😊",
    "Sənin adını eşidəndə ürəyim titrəyir. 🙌",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 💫",
    "Sənin sevgin qəlbimi istilədir. 🌸",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ❤️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🔥",
    "Səninlə hər günüm bir bayramdır. 🌸",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🙌",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌟",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌟",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🔥",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌟",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🙌",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌟",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌟",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır. 🌟",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🙌",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🙌",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌹",
    "Hər anın səninlə bir ömür kimidir. 😊",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌟",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır. 🌟",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌸",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🙌",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌸",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🎶",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌟",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌸",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌹",
    "Sənin sevgin qəlbimi istilədir. ☀️",
    "Sənin baxışların mənə yeni bir dünya açır. 💫",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 💫",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🎶",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. ☀️",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 😊",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 😊",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🔥",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🔥",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌹",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🔥",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🎶",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌹",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır. ❤️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🔥",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🔥",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. ☀️",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌸",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌸",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır. 🙌",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 😊",
    "Sən mənim həyatımın ən parlaq ulduzusan. ❤️",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌟",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 💫",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ❤️",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌸",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌹",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ❤️",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌟",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 💫",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ❤️",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🎶",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 💫",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌹",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 😊",
    "Hər anın səninlə bir ömür kimidir. 🔥",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 😊",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌟",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌟",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🙌",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌟",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌟",
    "Sənin adını eşidəndə ürəyim titrəyir. 🎶",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌸",
    "Sənin sevgin qəlbimi istilədir. 💫",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌟",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌸",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌹",
    "Sənin adını eşidəndə ürəyim titrəyir. ☀️",
    "Hər anın səninlə bir ömür kimidir. 💫",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 😊",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. ☀️",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 😊",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🎶",
    "Sənin baxışların mənə yeni bir dünya açır. ☀️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🙌",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. ☀️",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌟",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🔥",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🔥",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🙌",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 🌸",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 💫",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌟",
    "Hər anın səninlə bir ömür kimidir. 🙌",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🙌",
    "Sənin sevgin qəlbimi istilədir. 🔥",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🙌",
    "Sənin adını eşidəndə ürəyim titrəyir. 🎶",
    "Hər anın səninlə bir ömür kimidir. 🎶",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🔥",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır. 🎶",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🔥",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 💫",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ☀️",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🙌",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🔥",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌹",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🙌",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 😊",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. ☀️",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. ❤️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌟",
    "Sənin adını eşidəndə ürəyim titrəyir. 🙌",
    "Hər anın səninlə bir ömür kimidir. 💫",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır. 🎶",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌹",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 😊",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🎶",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌹",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🎶",
    "Sənin adını eşidəndə ürəyim titrəyir. 🎶",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🌹",
    "Sənin sevgin qəlbimi istilədir. 🌟",
    "Sənin baxışların mənə yeni bir dünya açır. ☀️",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 💫",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 💫",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌹",
    "Hər anın səninlə bir ömür kimidir. 🌟",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌸",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 😊",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. ❤️",
    "Hər baxışınla mənə bir dünya bəxş edirsən. ☀️",
    "Sənin adını eşidəndə ürəyim titrəyir. 🎶",
    "Hər anın səninlə bir ömür kimidir. 💫",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ☀️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🌹",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🎶",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir. ❤️",
    "Hər anın səninlə bir ömür kimidir.",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🙌",
    "Sənin sevgin qəlbimi istilədir. ❤️",
    "Sənin baxışların mənə yeni bir dünya açır. 🙌",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən.",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır. 😊",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🌹",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. 😊",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır.",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. 🌸",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir. 🙌",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 💫",
    "Sənin adını eşidəndə ürəyim titrəyir. 🌹",
    "Hər anın səninlə bir ömür kimidir. 🔥",
    "Sən mənim həyatımın ən parlaq ulduzusan. 🎶",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🎶",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ❤️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən. 🔥",
    "Səninlə hər günüm bir bayramdır. 🌟",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən.",
    "Sənin adını eşidəndə ürəyim titrəyir.",
    "Hər anın səninlə bir ömür kimidir. ❤️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir.",
    "Sənin baxışların mənə yeni bir dünya açır. 🌹",
    "Hər gecə sənə dua edirəm, çünki sən mənim hər şeyimsən. ☀️",
    "Sən mənim ürəyimin ən dərin sirrini bilirsən.",
    "Səninlə hər günüm bir bayramdır.",
    "Sənin varlığın mənim həyatımın ən böyük hədiyyəsidir.",
    "Hər baxışınla mənə bir dünya bəxş edirsən. 🌸",
    "Sənin adını eşidəndə ürəyim titrəyir. 🔥",
    "Hər anın səninlə bir ömür kimidir. ☀️",
    "Sən mənim həyatımın ən parlaq ulduzusan.",
    "Sənin sevgin qəlbimi istilədir. 🌹",
    "Sənin baxışların mənə yeni bir dünya açır. ☀️",
]




import asyncio
import random
from pyrogram import Client, filters
from pyrogram.types import Message, InlineKeyboardMarkup, InlineKeyboardButton

# Botun məlumatları
API_ID = 123456  # Telegram API ID
API_HASH = "your_api_hash"  # Telegram API Hash
BOT_TOKEN = "your_bot_token"  # Bot Token

# Bot müştərisi
rzayeff = Client("tag_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

# Gözəl sözlər, şeir parçaları və musiqi mətnləri
beautiful_phrases = [
    "Sən bu qrupun qəlbisin! ❤️",
    "Sənin enerjin bu qrupa həyat verir! 🌟",
    "Səninlə dost olmaq bir şərəfdir! 🙌",
    "Sən bu qrupun ən parlaq günəşisən! ☀️",
    "Hər anın xoşbəxtliklə dolsun! 🌸"
]

# Tağ etmə prosesinin dayandırılması üçün flag
tagging_in_progress = False

# Inline düymələri göndərən menyu
@rzayeff.on_message(filters.command(["tag", "tağ", "tagger", "menu", "menyu"], prefixes=["/", "!", "."]) & filters.group)
async def show_menu(client: Client, message: Message):
    keyboard = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton("😍 Sözlərlə tağ", callback_data="tag_with_phrases"),
                InlineKeyboardButton("😉 Beş'li tağ", callback_data="tag_five"),
            ],
            [
                InlineKeyboardButton("☑️ Tağı dayandır", callback_data="stop_tagging"),
            ]
        ]
    )
    await message.reply_text("Tağ Menyusu:", reply_markup=keyboard)

# Callback data-ları idarə edən funksiya
@rzayeff.on_callback_query()
async def handle_callbacks(client: Client, callback_query):
    global tagging_in_progress
    data = callback_query.data
    chat_id = callback_query.message.chat.id

    if data == "tag_with_phrases":
        await tag_with_phrases(client, callback_query.message)
    elif data == "tag_five":
        await tag_five(client, callback_query.message)
    elif data == "stop_tagging":
        tagging_in_progress = False
        await callback_query.message.reply_text("Tağ prosesi dayandırıldı.")
    await callback_query.answer()

# Sözlərlə tağ edən funksiya
async def tag_with_phrases(client: Client, message: Message):
    global tagging_in_progress
    chat_id = message.chat.id

    if tagging_in_progress:
        await message.reply_text("Tağ prosesi artıq davam edir. Lütfən, bitməsini gözləyin.")
        return

    tagging_in_progress = True
    await message.reply_text("Sözlərlə tağ prosesi başladı...")

    async for member in client.get_chat_members(chat_id):
        if not tagging_in_progress:
            await message.reply_text("Tağ prosesi dayandırıldı.")
            return

        if member.user.is_bot:
            continue

        phrase = random.choice(beautiful_phrases)
        user_tag = (
            f"@{member.user.username}"
            if member.user.username
            else f"[{member.user.first_name}](tg://user?id={member.user.id})"
        )
        tag_message = f"{user_tag}, {phrase}"
        await client.send_message(chat_id, tag_message, disable_web_page_preview=True)
        await asyncio.sleep(3)

    tagging_in_progress = False
    await message.reply_text("Tağ prosesi tamamlandı!")

# Beş'li tağ edən funksiya
async def tag_five(client: Client, message: Message, custom_message=None):
    global tagging_in_progress
    chat_id = message.chat.id

    if tagging_in_progress:
        await message.reply_text("Tağ prosesi artıq davam edir. Lütfən, bitməsini gözləyin.")
        return

    tagging_in_progress = True
    await message.reply_text("Beş'li tağ prosesi başladı...")

    members = []
    async for member in client.get_chat_members(chat_id):
        if member.user.is_bot:
            continue
        user_tag = (
            f"@{member.user.username}"
            if member.user.username
            else f"[{member.user.first_name}](tg://user?id={member.user.id})"
        )
        members.append(user_tag)

    for i in range(0, len(members), 5):
        if not tagging_in_progress:
            await message.reply_text("Tağ prosesi dayandırıldı.")
            return

        tag_group = members[i:i+5]
        tag_message = " ".join(tag_group)
        if custom_message:
            tag_message += f"\n\n{custom_message}"

        await client.send_message(chat_id, tag_message, disable_web_page_preview=True)
        await asyncio.sleep(3)

    tagging_in_progress = False
    await message.reply_text("Beş'li tağ prosesi tamamlandı!")

# /btag əmri ilə beş'li tağ
@rzayeff.on_message(filters.command("btag", prefixes=["/", "!", "."]) & filters.group)
async def btag_command(client: Client, message: Message):
    custom_message = message.text.split(maxsplit=1)[1] if len(message.text.split()) > 1 else None
    await tag_five(client, message, custom_message)

# Botu işə salırıq
if __name__ == "__main__":
    rzayeff.run()
